apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-ljag
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-ljag
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-ljag
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-ljag
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-ljag
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-vnbo-tenant/dotnet-component/devfile-sample-dotnet60-basic-ljag@sha256:83c9e7dbc1511f5f1c6d6e52db6e9e24ecaaced67137ba5c4be587e1064631fc
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
